# Generated by Django 5.2 on 2025-08-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='titulo_corto',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
