# Generated by Django 5.2 on 2025-08-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0002_certificado_titulo_corto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='titulo_corto',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
