# Generated by Django 5.1.7 on 2025-03-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0003_alter_educacion_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
