# Generated by Django 5.1.7 on 2025-03-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0004_certificados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificados',
            old_name='fecha_inicio',
            new_name='fecha_expedicion',
        ),
        migrations.RemoveField(
            model_name='certificados',
            name='fecha_fin',
        ),
    ]
