# Generated by Django 5.1.7 on 2025-03-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0005_rename_fecha_inicio_certificados_fecha_expedicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificados',
            name='id_credencial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificados',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='certificados',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
