# Generated by Django 5.1.7 on 2025-03-08 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0006_certificados_id_credencial_certificados_imagen_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificados',
        ),
        migrations.DeleteModel(
            name='Educacion',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='experiencia',
            name='mes_inicio',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 17, 39, 4, 208576, tzinfo=datetime.timezone.utc), unique_for_month=True),
        ),
    ]
