# Generated by Django 5.1.7 on 2025-03-08 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0007_delete_certificados_delete_educacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='anio_inicio',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 17, 39, 17, 346337, tzinfo=datetime.timezone.utc), unique_for_year=True),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='mes_inicio',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 17, 39, 17, 346337, tzinfo=datetime.timezone.utc), unique_for_month=True),
        ),
    ]
