# Generated by Django 5.1.7 on 2025-03-09 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0012_certificados_educacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificados',
            new_name='Certificado',
        ),
    ]
