# Generated by Django 5.1.7 on 2025-03-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0015_contacto_delete_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='nombre_archivo',
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo_archivo',
            field=models.CharField(choices=[('curriculum', 'Curriculum'), ('vida_laboral', 'Vida Laboral'), ('otro', 'Otro')], default='Curriculum', max_length=50),
        ),
    ]
