# Generated by Django 5.1.7 on 2025-03-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0016_remove_contacto_nombre_archivo_contacto_tipo_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='nombre',
            new_name='nombre_persona',
        ),
    ]
