# Generated by Django 5.1.7 on 2025-03-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0017_rename_nombre_contacto_nombre_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='url',
        ),
    ]
