# Generated by Django 5.1.7 on 2025-03-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0018_remove_contacto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_archivo',
            field=models.CharField(choices=[('Curriculum', 'Curriculum'), ('Vida Laboral', 'Vida Laboral'), ('Otro', 'Otro')], default='Curriculum', max_length=50),
        ),
    ]
