# Generated by Django 5.1.7 on 2025-03-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0019_experiencia_imagen_alter_contacto_tipo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='experiencia/'),
        ),
    ]
