# Generated by Django 5.1.7 on 2025-03-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0021_alter_experiencia_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='educacion/'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Introduce cada punto con un salto de línea y el símbolo', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Introduce cada punto con un salto de línea y el símbolo', null=True, verbose_name='Descripción'),
        ),
    ]
